In [ ]:
np practice jupyter-lab

In [3]:
import numpy as np
from fractions import Fraction

In [20]:
dzielenie = np.divide([Fraction(-16, 1), -Fraction(12, 1), Fraction(3 - 7, 1)], [Fraction(-24, 1), 5, -5 + 8])
dzielenie
print(dzielenie)

[Fraction(2, 3) Fraction(-12, 5) Fraction(-4, 3)]


In [23]:
lista = np.array([7, -3, -Fraction(1, 5), 1 + Fraction(2, 3), -.8, float(4 + Fraction(1, 2)), -.25])
l_odwrotna = np.multiply(lista, -1)
l_odwrotna

array([-7, 3, Fraction(1, 5), Fraction(-5, 3), 0.8, -4.5, 0.25],
      dtype=object)

'Jaką liczbą jest iloraz.'

a

In [36]:
iloraz = np.divide([-14, -7 - Fraction(1, 2), 0, 14], [-2, 7, -12, -2])
iloraz

array([7.0, Fraction(-15, 14), -0.0, -7.0], dtype=object)

In [38]:
iloraz[iloraz > 0]

array([7.0], dtype=object)

In [39]:
iloraz[iloraz < 0]

array([Fraction(-15, 14), -7.0], dtype=object)

In [40]:
iloraz[iloraz == 0]

array([-0.0], dtype=object)

b

In [41]:
iloraz2 = np.divide([-2.1, -4.2, 4.25, -0], [.3, -7, 2.5, -10])
iloraz2

array([-7. ,  0.6,  1.7, -0. ])

In [42]:
iloraz2[iloraz2 > 0]

array([0.6, 1.7])

In [43]:
iloraz2[iloraz2 < 0]

array([-7.])

In [44]:
iloraz2[iloraz2 == 0]

array([-0.])

Zadanie 4.7

In [43]:
a = np.array([[Fraction(-3, 4), Fraction(-15, 28), Fraction(21, 40), Fraction(-7, 15)], [Fraction(-5, 8), Fraction(9, 14), Fraction(-63, 80), Fraction(-7, 20)]])

In [44]:
a_div = np.divide(a[0], a[1])
a_div

array([Fraction(6, 5), Fraction(-5, 6), Fraction(-2, 3), Fraction(4, 3)],
      dtype=object)

In [52]:
a_check = np.multiply(a[1], a_div)
a_check

array([Fraction(-3, 4), Fraction(-15, 28), Fraction(21, 40),
       Fraction(-7, 15)], dtype=object)

In [55]:
b = np.array([[-36, -3 - Fraction(1, 3), 5 + Fraction(3, 7), -9 - Fraction(5, 8)], [-9, -2 - Fraction(2, 9), -2  - Fraction(2, 3), -2 + Fraction(-3, 4)]])
b

array([[-36, Fraction(-10, 3), Fraction(38, 7), Fraction(-77, 8)],
       [-9, Fraction(-20, 9), Fraction(-8, 3), Fraction(-11, 4)]],
      dtype=object)

In [57]:
b_div = np.divide(b[0], b[1])
b_div

array([4.0, Fraction(3, 2), Fraction(-57, 28), Fraction(7, 2)],
      dtype=object)

In [64]:
b_check = np.multiply(b_div, b[1])
b_check.astype(float)

array([-36.        ,  -3.33333333,   5.42857143,  -9.625     ])

In [66]:
c = np.array([[-4.2, -3 - Fraction(3, 8), -2.4, -3 - Fraction(3, 4)], [.6, .9, -.24, 2.5]])
c

array([[-4.2, Fraction(-27, 8), -2.4, Fraction(-15, 4)],
       [0.6, 0.9, -0.24, 2.5]], dtype=object)

In [68]:
c_div = np.divide(c[0], c[1])
c_div

array([-7.000000000000001, -3.75, 10.0, -1.5], dtype=object)

In [73]:
c_check = np.multiply(c_div, c[1])
c_check.astype(float)

array([-4.2  , -3.375, -2.4  , -3.75 ])

Zadanie 7.5

In [130]:
a = np.array([-2 - Fraction(2, 3)])
x = np.divide(a[0], 4.8)
x = Fraction(x)
x.limit_denominator()

Fraction(-5, 9)

In [135]:
a_check = np.divide(a[0], x)
float(a_check.limit_denominator())

4.8

b)

In [15]:
b = np.divide(5 + Fraction(3, 7), -2 - Fraction(1, 28))
float(b)

-2.6666666666666665

In [142]:
b_check = np.divide(5 + Fraction(3, 7), b)
float(b_check)

-2.0357142857142856

c)

In [152]:
c = np.prod([-1.1, 2 + Fraction(1, 2)])
c

-2.75

In [153]:
c_check = np.divide(c, -1.1)
c_check

2.5

d)

In [1]:
# d = np.linalg.solve([[6], []], [3])
# d

In [167]:
d=np.divide(-6.75, -4 - Fraction(1, 2))
d

1.5

In [168]:
d_check = np.multiply(-4 - Fraction(1, 2), d)
d_check

-6.75

In [17]:
e = np.divide(Fraction(-4, 5), -.5)
Fraction(e).limit_denominator()

Fraction(8, 5)

In [173]:
e_check = np.prod([e, -0.5])
Fraction(e_check).limit_denominator()

Fraction(-4, 5)

In [19]:
f = np.prod([-2 - Fraction(1, 9), -1.8])
Fraction(f).limit_denominator()

Fraction(19, 5)

In [176]:
f_check = np.divide(f, -2 -Fraction(1,9))
f_check

-1.8

Zadanie 7.6

In [179]:
a = np.divide(np.sum([-3.5, -5 -Fraction(1, 3)]), 1 + Fraction(5, 12))
a

-6.235294117647058

Zadanie 7.7

In [189]:
a = np.divide(-3 -Fraction(1, 8), -6 -Fraction(1, 4))
a1 = np.multiply(a, -4 - Fraction(2, 3))
a1

Fraction(-7, 3)

Zadanie 7.8

In [196]:
a = np.divide(-180, 5)
a1 = np.prod([a, 7])
a1

-252.0

In [197]:
b = np.prod([np.divide(-3 -Fraction(1, 3), 5), 11])
b

Fraction(-22, 3)

In [199]:
c = np.divide(-6.75, 2.5)
c

-2.7

In [201]:
d = np.prod([0.2, -245])
d1 = np.divide(d, 7)
d2 = np.multiply(d1, 8)
d2

-56.0

Zadanie 7.9

In [11]:
d_diff = np.subtract(4 +Fraction(2, 3), -3.5)
d_diff

8.166666666666668

In [10]:
d_sum =np.sum([4 + Fraction(2, 3), -3.5])
d_sum

1.166666666666667

In [22]:
d_div = np.divide(d_diff, d_sum)
round(d_div)

7

Zad 7.10

In [27]:
a = np.multiply(np.subtract(np.divide(-7 - Fraction(1, 5), 0.5), np.multiply(-7 - Fraction(1, 5), 0.5)), 0.2)
a

-2.16

In [43]:
import math

Rozdział 8

In [65]:
d = np.power(Fraction(-2, 5), 3)
d

Fraction(-8, 125)

In [68]:
o = np.power(-6, 1)
o

-6

In [69]:
o1 = np.power(10, 0)
o1

1

In [70]:
o2 =np.power(-8, 0)
o2

1

In [71]:
o3 = np.power(-1.3, 0)
o3

1.0

In [72]:
o4 = np.power(Fraction(-5, 6), 0)
o4

Fraction(1, 1)

In [ ]:
Zadanie 2

In [73]:
a = np.power(4, 2)
a

16

In [75]:
b = np.power(Fraction(2, 3), 3)
b

Fraction(8, 27)

In [76]:
c= np.power(12, 1)
c

12

In [79]:
d = np.power(4 + Fraction(1, 3), 0)
d

Fraction(1, 1)

In [ ]:
Zadanie 3 

In [82]:
a = np.power([-3, Fraction(-2, 5), -2, Fraction(-2, 3), -Fraction(1, 2), -1], [1, 2, 3, 4, 5, 6])
a

array([-3, Fraction(4, 25), -8, Fraction(16, 81), Fraction(-1, 32), 1],
      dtype=object)

In [ ]:
Zad 8.2

In [83]:
a3 = np.power(-6, 3)
a3

-216

In [85]:
b1= np.power(-2 - Fraction(1, 3), 2)
b1

Fraction(49, 9)

In [87]:
b2 =np.power(3 + Fraction(1, 3), 3)
float(b2)

37.03703703703704

In [89]:
b3 = np.power(-2 - Fraction(3, 4), 2)
float(b3)

7.5625

In [91]:
b4 = np.power(-7 - Fraction(1, 2), 2)
float(b4)

56.25

In [92]:
c1 = np.power(-.5, 2)
c1

0.25

In [93]:
c2 = np.power(1.5, 2)
c2

2.25

In [94]:
c3 = np.power(-1.6, 2)
c3

2.5600000000000005

In [98]:
c4 = np.power(-.3, 3)
Fraction(c4).limit_denominator()

Fraction(-27, 1000)

Zad 8.3

In [100]:
a1 = np.power(-3 - Fraction(1, 3), 1)
a1

Fraction(-10, 3)

In [101]:
a2 = np.power(-10.1, 0)
a2

1.0

In [102]:
a3 = np.power(6 + Fraction(5, 6), 0)
a3

Fraction(1, 1)

In [103]:
a4 = np.power(8 + Fraction(5, 7), 1)
a4

Fraction(61, 7)

In [106]:
b1 = np.power(Fraction(3, 4), 2)
b1

Fraction(9, 16)

In [107]:
b2 = np.power(-Fraction(3, 4), 2)
b2

Fraction(9, 16)

In [109]:
b3 = np.power(Fraction(1, 2), 3)
b3

Fraction(1, 8)

In [110]:
b3 = np.power(-Fraction(1, 2), 3)
b3 

Fraction(-1, 8)

In [113]:
c1 = np.sum(np.power([Fraction(1, 3), Fraction(-1, 2)], [2, 2]))
c1

Fraction(13, 36)

In [120]:
c2 = np.subtract(np.power(Fraction(1, -3), 2), np.power(Fraction(-1, 2), 2))
c2               

Fraction(-5, 36)

Zad 8.4

In [128]:
a = np.subtract(np.multiply(.5, -Fraction(1, 3)), Fraction(1, 18))
print(a)
print(Fraction(a).limit_denominator())

-0.2222222222222222
-2/9


In [156]:
b= np.multiply(np.power(np.subtract(1.5, 1 + Fraction(3, 4)), 2), 3 + Fraction(1, 2))
Fraction(b)

Fraction(7, 32)

In [167]:
c = np.subtract(Fraction(1, 2), np.power(-0.5, 2)) + np.power(-Fraction(1, 4), 2)
Fraction(c)

Fraction(5, 16)

In [168]:
c = np.sum([np.subtract(Fraction(1, 2), np.power(-0.5, 2)), np.power(-Fraction(1, 4), 2)])
Fraction(c)

Fraction(5, 16)

In [174]:
d = np.subtract(np.divide(np.power(-2 - Fraction(2, 3), 2), - Fraction(2, 3)), -4 - Fraction(5, 6))
d

Fraction(-35, 6)

Zad 8.5

In [94]:
a = -811 ** 7 
aa = 428 ** 8
a1 = max(a, aa)
a, aa, 'max to: ', a1  

(-230752268637185668771,
 1126030494814647156736,
 'max to: ',
 1126030494814647156736)

-230752268637185668771

Rozdział 9.

In [70]:
a = np.sqrt([36, 16])
a

array([6., 4.])

In [10]:
a1 = np.cbrt([125, 343])
a1

array([5., 7.])

In [ ]:
a1 = np.cbrt(125)

In [12]:
a3 = np.cbrt(2 + 10/27)
a3

1.3333333333333333

In [15]:
a4 = np.cbrt(1 + 61/64)
a4

1.25

In [ ]:
Zad 9.2

In [20]:
a1 = np.sqrt(np.power(3, 2))
a1

3.0

In [22]:
a1 = np.cbrt(np.power(3, 3))
a1

3.0

In [27]:
a4 = np.sqrt(np.power(11, 2))
Fraction(a4).limit_denominator()

Fraction(11, 1)

In [32]:
b1 = np.sqrt(np.power(1/5, 2))
b1

0.2

In [35]:
b4 = np.sqrt(np.power(5/3, 2))
Fraction(b4).limit_denominator()

Fraction(5, 3)

In [38]:
d4 = np.cbrt(np.power(1 + 1/2, 3))
d4

1.5



Zad. 9.3



In [39]:
a = np.subtract(np.sqrt(25), np.sqrt(36))
a

-1.0

In [42]:
b = np.sum([np.sqrt(169), np.sqrt(16)])
b

17.0

In [45]:
c = np.subtract(np.sqrt(81), -np.sqrt(49))
c

16.0

In [46]:
d = np.sum([np.sqrt(36), np.sqrt(64), -np.sqrt(25)])
d

9.0

In [47]:
e= np.sum([np.cbrt(8), -np.cbrt(27), np.cbrt(1)])
e

0.0

In [50]:
f= np.sum([np.cbrt(27), (-np.cbrt(64)), -(-np.cbrt(125))])
f

4.0

In [51]:
g = np.sum([np.cbrt(125), np.sqrt(25), -np.cbrt(1000)])
g

0.0

In [53]:
h = np.subtract(np.sum([np.sqrt(169), np.sqrt(36)]), np.cbrt(216))
h

13.0

In [ ]:
Zad 9.4

In [57]:
a = np.sum([np.multiply(-2, np.sqrt(25)), np.divide(np.sqrt(64), np.sqrt(16))])
a

-8.0

In [58]:
b = np.subtract(np.divide(np.cbrt(125), -5), np.multiply(-3, np.sqrt(16)))
b

11.0

In [62]:
c = np.sum([np.multiply(-np.cbrt(64), np.power(-2, 2)), np.multiply(Fraction(1, 2), np.sqrt(100))])
c

-11.0

In [69]:
d = np.divide(np.sum([np.multiply(np.sqrt(4), np.sqrt(49)), np.cbrt(27)]), np.multiply(np.cbrt(8), np.sum([np.cbrt(125), np.sqrt(4)])))
Fraction(d).limit_denominator()

Fraction(17, 14)

In [73]:
e = np.sum([np.multiply(np.cbrt(8/125), np.sqrt(25)), np.divide(np.sum([np.cbrt(27), np.sqrt(16)]), -7)])
Fraction(e).limit_denominator()

Fraction(1, 1)

Zadanie 9.5

In [75]:
a = np.sqrt(np.sum([np.power(4, 2), np.power(3, 2)]))
a

5.0

In [116]:
b = np.subtract(np.sqrt(32), np.sqrt(49))
b = float('{:.3f}'.format(b))
b

-1.343

In [83]:
c = np.subtract(np.multiply(-np.sqrt(16), np.sqrt(1/16)), np.multiply(np.sqrt(4), np.power(-Fraction(1, 2), 2)))
c

-1.5

In [110]:
d = np.subtract(np.power(np.sqrt(2/5), 2), np.power(np.cbrt(3/4), 3))
d = float('{:.2f}'.format(d))
Fraction(d).limit_denominator()

Fraction(-7, 20)

In [102]:
e = np.power(np.subtract(np.cbrt(27), np.sqrt(4)), 2)
e

1.0

In [106]:
f = np.sum([np.multiply(np.cbrt(1/8), np.sqrt(36)), np.multiply(np.power(-2, 3), -np.sqrt(2 + 1/4))])
f

15.0

In [108]:
g = np.sum([np.power(-3, 3), np.sqrt(49), np.sqrt(np.subtract(np.power(5, 2), np.power(4, 2))), np.sqrt(144)])
g

-5.0

Rozdział 10

In [ ]:
Zadanie 1

In [124]:
a = np.sum([np.multiply(np.subtract(7, 11), np.power(-2, 3)), np.divide(np.sqrt(100), np.sum([-2, -3]))])
a

30.0

In [127]:
a1 = np.sum([np.multiply(np.power(-3, 2), 5), np.multiply(6, -1)])
a1

39

In [128]:
a2 = np.subtract(np.multiply(np.power(2, 3), -4), np.multiply(-3, -2))
a2

-38

In [130]:
a3 = np.sum([np.multiply(-10, np.sqrt(25)), np.multiply(np.power(3, 3), -2)])
a3

-104.0

In [133]:
a4 = np.subtract(np.multiply(-4, np.power(2, 2)), np.multiply(np.sqrt(9), -3))
a4

-7.0

In [135]:
b1 = np.subtract(np.multiply(2, -.4), np.multiply(.5, -3))
b1

0.7

In [139]:
b2 = np.subtract(np.multiply(-2.5, -8), np.multiply(np.power(2, 2), -5))
b2

40.0

In [141]:
b3 = np.sum([np.multiply(np.sqrt(81), Fraction(1, 3)), np.divide(3, -1 - Fraction(1, 2))])
b3

1.0

In [143]:
b4 = np.sum([np.divide(-125, np.power(-5, 2)), np.multiply(-4.5, 8)])
b4

-41.0

In [ ]:
Zad 10.2

In [171]:
temperatura = np.array([[-2, -5, -2, 0, 2, 5, 7], [4, 3, -8, -10, -4, 0, 8], [6, 3, 3, 2, -4, -4, -5]], dtype='int64')
max_temp = np.max([np.mean(temperatura[0]), np.mean(temperatura[1]), np.mean(temperatura[2])])
max_temp_index = np.argmax(max_temp)
max_temp_index, max_temp

(0, 0.7142857142857143)

In [ ]:
Zad 10.3

In [178]:
a = np.array([-3.5 * 2, -2**2 * .5 * -6, np.sqrt(25) -2 * -4.5, (-2**3 * -1.25) / 2, np.cbrt(8) * -3 + 4 * 3.5, (3**2 - np.sqrt(49)) / -2])
np.sort(a)

array([-7., -1.,  5.,  8., 12., 14.])

In [ ]:
Zad 10.4

In [196]:
a = np.sum([np.power(2, 3), np.multiply(3, -2), np.sqrt(2 + 7/9)])
str(Fraction(a).limit_denominator().numerator) + '/' + str(Fraction(a).limit_denominator().denominator)

3.666666666666667

In [197]:
b = np.subtract(np.multiply(-3 - np.divide(1, 3), np.divide(3, 5)), np.divide(-6 - 1/4, 2))
Fraction(b)

Fraction(9, 8)

In [193]:
c = np.sum([np.subtract(np.power(-1.5, 3), np.multiply(5, -1/8)), np.sqrt(np.multiply(2, 18))])
c

3.25

In [195]:
d = np.sum([np.subtract(np.multiply(-2.5, -4), 4*-15), -8 + 3])
d

65.0

In [ ]:
Zad 10.5

In [199]:
a = np.sum([np.power(-3.25, 2), np.multiply(-2, -4)])
a

18.5625

In [223]:
a = (-3.25)**2 + (-2 * -4)
a

18.5625

In [224]:
b= np.subtract(np.multiply(-3.5, 5), np.power(-3, 3))
b

9.5

In [227]:
c= np.sum([np.multiply(2.25, -1 -Fraction(1, 9)), np.power(4, 2)])
c

13.5

In [229]:
d = np.subtract(np.multiply(-3 -1/2, 4), np.sqrt(25))
d

-19.0

In [230]:
e = np.subtract(np.multiply(-6 -2/3, -0.4), np.sqrt(49))
e

-4.333333333333333

In [232]:
f = np.sum([np.multiply(np.power(1.5, 3), 4 + 4/9), np.multiply(np.sqrt(64), -5)])
f

-25.0

In [233]:
g = np.subtract(np.power(-2 -1/2 + 3, 2), np.power(-4 + 3.5, 2))
g

0.0

In [366]:
h = np.sum([np.subtract(np.multiply(-2 -2/3, -3 - 3/4), np.multiply(np.power(-3, 2), -1/3)), np.multiply(np.power(2, 3), -.5)])
h

9.0

In [ ]:
Zadanie 10.6

In [248]:
a = np.divide(np.sum([13.2, 2.3]), 5)
a

3.1

In [249]:
a_check = np.subtract(np.multiply(5, a), 2.3)
a_check

13.2

In [255]:
b = np.divide(np.subtract(-5/12, 6.25), 3 + 1/3)
b

-2.0

In [258]:
b_check = np.sum([np.multiply(3 + 1/3, b), 6.25])
Fraction(b_check).limit_denominator()

Fraction(-5, 12)

In [261]:
c= np.divide(np.sum([2.2, 6.2]), 2.4)
c

3.5000000000000004

In [262]:
c_check = np.subtract(np.multiply(-2.4, c), -6.2)
c_check

-2.2

In [364]:
d = np.divide(np.sum([-16, 3 * 2]), -2.5)
d

4.0

In [365]:
d_check = np.sum([np.multiply(-2.5, d), np.multiply(3, -2)])
d_check

-16.0

In [288]:
e = np.divide(np.sum([14 + 2/3, np.multiply(20, 1/3)]), np.sum([2, 2/3]))
e

8.0

In [291]:
c_check = np.subtract(np.multiply(20, -1/3), (-2 -2/3) * e)
c_check

14.666666666666666

In [336]:
f = np.divide(np.sum([-24, 9]), 2.5)
f

-6.0

In [337]:
f_check = np.subtract(np.multiply(2.5, f), np.power(3, 2))
f_check

-24.0

In [379]:
g = np.divide(np.sum([np.power(-5, 0), -np.multiply(15.5, 2)]), np.sqrt(64))
g

4.0

In [382]:
g_check = np.subtract(np.multiply(np.sqrt(64), g), -np.multiply(15.5, -2))
g_check

1.0

In [383]:
h = np.divide(np.sum([np.sqrt(16), np.multiply(4, 3.5)]), np.power(-3, 2))
h

2.0

In [384]:
h_check = np.subtract(np.multiply(np.power(-3, 2), h), np.multiply(4, 3.5))
h_check

4.0

In [ ]:
Zadanie 10.7

In [385]:
a = np.multiply(np.sum([5, Fraction(1, 3)]), np.sum([4, Fraction(1, 4)]))
a

Fraction(68, 3)

In [386]:
a_aug = np.multiply(np.sum([5, Fraction(1, 3), 2, Fraction(1, 2)]), np.sum([4, Fraction(1, 4), -1, -Fraction(1, 2)]))
a_aug

Fraction(517, 24)

In [390]:
a_aug - a

Fraction(-9, 8)

In [ ]:
Zadanie 10.8

In [391]:
a = np.divide(np.multiply(np.sqrt(144), np.power(-1/2, 2)), -1/4)
a

-12.0

In [402]:
b = np.divide(np.prod([np.power(-4, 3), 3, -2.5]), np.subtract(np.power(5, 2), np.sqrt(81)))
b

30.0

In [ ]:
Zadanie 10.9

In [434]:
dł_boków = np.array([15.2, 8.4])
P = np.multiply(dł_boków[0], dł_boków[1])
P

127.67999999999999

In [435]:
a_dim = np.prod([2.5, 2, 4])
a_dim

20.0

In [447]:
P_dim = P - a_dim
P_dim

107.67999999999999

In [446]:
Ob = np.multiply(dł_boków, 2)
Ob_dim = np.subtract(np.sum(Ob), np.multiply(2.5, 8))
Ob_dim

27.200000000000003

In [ ]:
Zad 10.10

In [450]:
a = np.sqrt(np.sum([np.power(-3, 2), np.power(4, 2)]))
a

5.0

Rozdział 11

In [ ]:
Zad 11.1

In [458]:
a = np.array([2, -1/2, 0, -4, 2 + 1/2, -5, 3 + 1/2, 4, -1])
np.sort(a)

array([-5. , -4. , -1. , -0.5,  0. ,  2. ,  2.5,  3.5,  4. ])

In [460]:
np.flipud(np.sort(a))

array([ 4. ,  3.5,  2.5,  2. ,  0. , -0.5, -1. , -4. , -5. ])

In [ ]:
Zad 11.2

In [461]:
a = np.array([-3, 7, -3/4, 10, -5/6, -12, -.8, 8 + 1/2])
a

array([ -3.        ,   7.        ,  -0.75      ,  10.        ,
        -0.83333333, -12.        ,  -0.8       ,   8.5       ])

In [462]:
-a

array([  3.        ,  -7.        ,   0.75      , -10.        ,
         0.83333333,  12.        ,   0.8       ,  -8.5       ])

In [ ]:
Zad 11.3

In [464]:
a = np.array([-2, 8, -13.5, 0, 1/2, -7 + 3/4, 9 + 1/2, -5, -10 - 2/3, 7 + 1/3, 1, -3 - 1/5])
np.sort(a)

array([-13.5       , -10.66666667,  -6.25      ,  -5.        ,
        -3.2       ,  -2.        ,   0.        ,   0.5       ,
         1.        ,   7.33333333,   8.        ,   9.5       ])

In [ ]:
Zadanie 11.4

In [6]:
a1 = np.add(-3/4, 1 + 1/3)
Fraction(a1).limit_denominator()

Fraction(7, 12)

In [9]:
a2 = np.add(1 + 1/2, -2 - 1/3)
Fraction(a2).limit_denominator()

Fraction(-5, 6)

In [12]:
a3 = np.add(-2-2/3, 3 + 1/3)
Fraction(a3).limit_denominator()

Fraction(2, 3)

In [39]:
a4 = np.subtract(-4.5, 2 + 4/5)
a4

-7.3

In [42]:
b1 = np.subtract(np.sum([np.subtract(2 + 2/3, 3.5), 1/4]), 1)
Fraction(b1).limit_denominator()

Fraction(-19, 12)

In [44]:
b2 = np.subtract(np.subtract(np.add(-2 -1/5, 1 + 4/5), 3 + 1/2), 1.5)
b2

-5.4

In [50]:
b2a = np.subtract(np.sum([-2 - 1/5, 1 + 4/5]), [3 + 1/2, 1.5])
b2a

array([-3.9, -1.9])

In [53]:
b3 = np.subtract(np.add(-np.subtract(2.5, 1 + 1/3), 3.5), 2 + 2/5)
Fraction(b3).limit_denominator()

Fraction(-1, 15)

In [62]:
b4 = np.subtract(np.subtract(4 + 1/3, 7.5), np.add(-2 - 1/2, 5.2))
Fraction(b4).limit_denominator(), b4

(Fraction(-88, 15), -5.866666666666667)

In [ ]:
Zadanie 11.5

In [67]:
a = np.array([2, -5, 1/7, -2/9, -3 - 1/2, 4 + 2/3, -12 - 1/3, -2.5])
for n in a:
    print(Fraction(n).limit_denominator())

2
-5
1/7
-2/9
-7/2
14/3
-37/3
-5/2


In [68]:
for n in -a:
    print(Fraction(n).limit_denominator())

-2
5
-1/7
2/9
7/2
-14/3
37/3
5/2


In [ ]:
Zadanie 11.6

In [70]:
a1 = np.multiply(-7, 3)
a1

-21

In [71]:
a2 = np.multiply(-8, -12)
a2

96

In [73]:
a3 = np.divide(80, -16)
a3

-5.0

In [74]:
a4 = np.divide(-75, -15)
a4

5.0

In [75]:
b1 = np.multiply(-2/5, 5/8)
b1

-0.25

In [76]:
b2 = np.multiply(-5/6, -8/15)
b2

0.4444444444444445

In [77]:
b3 = np.divide(Fraction(3, 4), Fraction(-5, 8))
b3

Fraction(-6, 5)

In [80]:
b4 = np.divide(-5/9, 7/18)
Fraction(b4).limit_denominator()

Fraction(-10, 7)

In [81]:
c1 = np.multiply(-3 -1/5, 2 +3/4)
c1

-8.8

In [83]:
c2 = np.multiply(-5 -5/8, -1 -1/9)
c2

6.25

In [87]:
c3 = np.divide(-3 -2/5, 1 +1/5)
Fraction(c3).limit_denominator()

Fraction(-17, 6)

In [90]:
c4 = np.divide(-16 -2/3, -2 -4/5)
Fraction(c4).limit_denominator(), c4

(Fraction(125, 21), 5.952380952380953)

Zadanie 11.7

In [97]:
a = np.array([-3, 0, -1 -5/7, 0, -3 -5/6, -5.25])
b = np.array([-4, -5, 0, -2/3, 0, 0])

a_plus_b = np.array([0, 0, 0, 1/6, 0, 0])
a_minus_b = np.array([0, 0, 0, 0, 3 + 7/12, 0])
a_x_b = np.array([0, -30, 0, 0, 0, 0])
a_podzielić_b = np.array([0, 0, -2 -1/2, 0, 0, 2.1])

In [99]:
a - b

array([ 1.        ,  5.        , -1.71428571,  0.66666667, -3.83333333,
       -5.25      ])

-0.40000000000000013