In [ ]:
np practice jupyter-lab

In [2]:
import numpy as np
from fractions import Fraction

In [20]:
dzielenie = np.divide([Fraction(-16, 1), -Fraction(12, 1), Fraction(3 - 7, 1)], [Fraction(-24, 1), 5, -5 + 8])
dzielenie
print(dzielenie)

[Fraction(2, 3) Fraction(-12, 5) Fraction(-4, 3)]


In [23]:
lista = np.array([7, -3, -Fraction(1, 5), 1 + Fraction(2, 3), -.8, float(4 + Fraction(1, 2)), -.25])
l_odwrotna = np.multiply(lista, -1)
l_odwrotna

array([-7, 3, Fraction(1, 5), Fraction(-5, 3), 0.8, -4.5, 0.25],
      dtype=object)

'Jaką liczbą jest iloraz.'

a

In [36]:
iloraz = np.divide([-14, -7 - Fraction(1, 2), 0, 14], [-2, 7, -12, -2])
iloraz

array([7.0, Fraction(-15, 14), -0.0, -7.0], dtype=object)

In [38]:
iloraz[iloraz > 0]

array([7.0], dtype=object)

In [39]:
iloraz[iloraz < 0]

array([Fraction(-15, 14), -7.0], dtype=object)

In [40]:
iloraz[iloraz == 0]

array([-0.0], dtype=object)

b

In [41]:
iloraz2 = np.divide([-2.1, -4.2, 4.25, -0], [.3, -7, 2.5, -10])
iloraz2

array([-7. ,  0.6,  1.7, -0. ])

In [42]:
iloraz2[iloraz2 > 0]

array([0.6, 1.7])

In [43]:
iloraz2[iloraz2 < 0]

array([-7.])

In [44]:
iloraz2[iloraz2 == 0]

array([-0.])

Zadanie 4.7

In [43]:
a = np.array([[Fraction(-3, 4), Fraction(-15, 28), Fraction(21, 40), Fraction(-7, 15)], [Fraction(-5, 8), Fraction(9, 14), Fraction(-63, 80), Fraction(-7, 20)]])

In [44]:
a_div = np.divide(a[0], a[1])
a_div

array([Fraction(6, 5), Fraction(-5, 6), Fraction(-2, 3), Fraction(4, 3)],
      dtype=object)

In [52]:
a_check = np.multiply(a[1], a_div)
a_check

array([Fraction(-3, 4), Fraction(-15, 28), Fraction(21, 40),
       Fraction(-7, 15)], dtype=object)

In [55]:
b = np.array([[-36, -3 - Fraction(1, 3), 5 + Fraction(3, 7), -9 - Fraction(5, 8)], [-9, -2 - Fraction(2, 9), -2  - Fraction(2, 3), -2 + Fraction(-3, 4)]])
b

array([[-36, Fraction(-10, 3), Fraction(38, 7), Fraction(-77, 8)],
       [-9, Fraction(-20, 9), Fraction(-8, 3), Fraction(-11, 4)]],
      dtype=object)

In [57]:
b_div = np.divide(b[0], b[1])
b_div

array([4.0, Fraction(3, 2), Fraction(-57, 28), Fraction(7, 2)],
      dtype=object)

In [64]:
b_check = np.multiply(b_div, b[1])
b_check.astype(float)

array([-36.        ,  -3.33333333,   5.42857143,  -9.625     ])

In [66]:
c = np.array([[-4.2, -3 - Fraction(3, 8), -2.4, -3 - Fraction(3, 4)], [.6, .9, -.24, 2.5]])
c

array([[-4.2, Fraction(-27, 8), -2.4, Fraction(-15, 4)],
       [0.6, 0.9, -0.24, 2.5]], dtype=object)

In [68]:
c_div = np.divide(c[0], c[1])
c_div

array([-7.000000000000001, -3.75, 10.0, -1.5], dtype=object)

In [73]:
c_check = np.multiply(c_div, c[1])
c_check.astype(float)

array([-4.2  , -3.375, -2.4  , -3.75 ])

Zadanie 7.5

In [130]:
a = np.array([-2 - Fraction(2, 3)])
x = np.divide(a[0], 4.8)
x = Fraction(x)
x.limit_denominator()

Fraction(-5, 9)

In [135]:
a_check = np.divide(a[0], x)
float(a_check.limit_denominator())

4.8

b)

In [136]:
b = np.divide(5 + Fraction(3, 7), -2 - Fraction(1, 28))
b

Fraction(-8, 3)

In [142]:
b_check = np.divide(5 + Fraction(3, 7), b)
float(b_check)

-2.0357142857142856

c)

In [152]:
c = np.prod([-1.1, 2 + Fraction(1, 2)])
c

-2.75

In [153]:
c_check = np.divide(c, -1.1)
c_check

2.5

d)

In [166]:
# d = np.linalg.solve([[6], []], [3])
# d

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [167]:
d=np.divide(-6.75, -4 - Fraction(1, 2))
d

1.5

In [168]:
d_check = np.multiply(-4 - Fraction(1, 2), d)
d_check

-6.75

In [169]:
e = np.divide(Fraction(-4, 5), -.5)
e

1.6

In [173]:
e_check = np.prod([e, -0.5])
Fraction(e_check).limit_denominator()

Fraction(-4, 5)

In [175]:
f = np.prod([-2 - Fraction(1, 9), -1.8])
f

3.8000000000000003

In [176]:
f_check = np.divide(f, -2 -Fraction(1,9))
f_check

-1.8

Zadanie 7.6

In [179]:
a = np.divide(np.sum([-3.5, -5 -Fraction(1, 3)]), 1 + Fraction(5, 12))
a

-6.235294117647058

Zadanie 7.7

In [189]:
a = np.divide(-3 -Fraction(1, 8), -6 -Fraction(1, 4))
a1 = np.multiply(a, -4 - Fraction(2, 3))
a1

Fraction(-7, 3)

Zadanie 7.8

In [196]:
a = np.divide(-180, 5)
a1 = np.prod([a, 7])
a1

-252.0

In [197]:
b = np.prod([np.divide(-3 -Fraction(1, 3), 5), 11])
b

Fraction(-22, 3)

In [199]:
c = np.divide(-6.75, 2.5)
c

-2.7

In [201]:
d = np.prod([0.2, -245])
d1 = np.divide(d, 7)
d2 = np.multiply(d1, 8)
d2

-56.0