In [ ]:
np practice jupyter-lab

In [16]:
import numpy as np
from fractions import Fraction

In [20]:
dzielenie = np.divide([Fraction(-16, 1), -Fraction(12, 1), Fraction(3 - 7, 1)], [Fraction(-24, 1), 5, -5 + 8])
dzielenie
print(dzielenie)

[Fraction(2, 3) Fraction(-12, 5) Fraction(-4, 3)]


In [23]:
lista = np.array([7, -3, -Fraction(1, 5), 1 + Fraction(2, 3), -.8, float(4 + Fraction(1, 2)), -.25])
l_odwrotna = np.multiply(lista, -1)
l_odwrotna

array([-7, 3, Fraction(1, 5), Fraction(-5, 3), 0.8, -4.5, 0.25],
      dtype=object)

'Jaką liczbą jest iloraz.'

a

In [36]:
iloraz = np.divide([-14, -7 - Fraction(1, 2), 0, 14], [-2, 7, -12, -2])
iloraz

array([7.0, Fraction(-15, 14), -0.0, -7.0], dtype=object)

In [38]:
iloraz[iloraz > 0]

array([7.0], dtype=object)

In [39]:
iloraz[iloraz < 0]

array([Fraction(-15, 14), -7.0], dtype=object)

In [40]:
iloraz[iloraz == 0]

array([-0.0], dtype=object)

b

In [41]:
iloraz2 = np.divide([-2.1, -4.2, 4.25, -0], [.3, -7, 2.5, -10])
iloraz2

array([-7. ,  0.6,  1.7, -0. ])

In [42]:
iloraz2[iloraz2 > 0]

array([0.6, 1.7])

In [43]:
iloraz2[iloraz2 < 0]

array([-7.])

In [44]:
iloraz2[iloraz2 == 0]

array([-0.])