In [1]:
import numpy as np

In [2]:
# Cross-entropy loss
class Loss_CategoricalCrossentropy(Loss):
    ...
    # Backward pass
    def backward(self, dvalues, y_true):
        # Number of samples
        samples = len(dvalues)
        # Number of labels in every sample
        # We'll use the first sample to count them
        labels = len(dvalues[0])
        # If labels are sparse, turn them into one-hot vector
        if len(y_true.shape) == 1:
            y_true = np.eye(labels)[y_true]
            # Calculate gradient
            self.dinputs = -y_true / dvalues
            # Normalize gradient
            self.dinputs = self.dinputs / samples

NameError: name 'Loss' is not defined

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.eye(5)[3]

array([0., 0., 0., 1., 0.])

In [16]:
softmax_outputs = np.array([[0.7, 0.1, 0.2],
                            [0.1, 0.5, 0.4],
                            [0.02, 0.9, 0.08]])

class_targets = [0, 1, 1]

In [17]:
for targ_idx, distribution in zip(class_targets, softmax_outputs):
    print(distribution[targ_idx])

0.7
0.5
0.9


In [22]:
softmax_outputs[[0, 1, 1], class_targets]

array([0.7, 0.5, 0.5])

In [20]:
softmax_outputs[range(len(softmax_outputs)), class_targets]

array([0.7, 0.5, 0.9])

In [23]:
-np.log(softmax_outputs[range(len(softmax_outputs)), class_targets])

array([0.35667494, 0.69314718, 0.10536052])

In [24]:
neg_log  = -np.log(softmax_outputs[range(len(softmax_outputs)), class_targets])

In [26]:
average_loss = np.mean(neg_log)

average_loss

0.38506088005216804