In [3]:
import math
import numpy as np

print(math.e)

2.718281828459045


In [4]:
layer_outputs = [4.8, 1.21, --2.385]

exp_values = []
for output in layer_outputs:
    exp_values.append(math.e ** output)

print('Expotentiated values')
print(exp_values)

Expotentiated values
[121.51041751873483, 3.353484652549023, 10.859062664920513]


In [5]:
# Normalization

# norm_base = sum(exp_values)
norm_val = []
for n in exp_values:
    norm_val.append(n / norm_base)

print('Normalized:')
print(norm_val)

NameError: name 'norm_base' is not defined

In [6]:
# Normalization w/ NumPy

layer_outputs = [4.8, 1.21, --2.385]
numpy_exp_values = np.exp(layer_outputs)
norm_values = numpy_exp_values / np.sum(numpy_exp_values)

print('Numpy expotentiated values:')
print(numpy_exp_values)
print('Numpy sum of normalized values:')
print(norm_values)

# Euler Expotentiation and Normalization in raw p
li = [[1, 2, 3]]

print('Euler Expotentiation and Normalization in raw p')
np.mean(li, axis=1), sum(li[0]) / len(li[0])


Numpy expotentiated values:
[121.51041752   3.35348465  10.85906266]
Numpy sum of normalized values:
[0.89528266 0.02470831 0.08000903]
Euler Expotentiation and Normalization in raw p


(array([2.]), 2.0)

In [17]:
inputs = np.array([[4.8, 1.21, 2.385],
                   [8.9, -1.81, 0.2],
                   [1.41, 1.051, 0.026]])

ex = np.exp(li - np.max(li, axis=1, keepdims=True))
pro = ex / np.sum(ex, axis=1, keepdims=True)
print(pro)

[[0.09003057 0.24472847 0.66524096]]


In [18]:
exp_values = np.exp(inputs)
print(np.exp(0))
# np sum axis=0 sumuje kolumny
# np sum axis=1 sumuje rzędy
sum = np.sum(inputs, axis=1, keepdims=True)
# print('Sum without axis:')
# print(sum)

1.0


In [21]:
# Softmax activation
class Activation_Softmax:

    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

        self.output = probabilities

# Some examples of dead/exploding neurons
# print(np.exp(-np.inf), np.exp(0))

softmax = Activation_Softmax()

softmax.forward([[-2, -1, 0]])
print(softmax.output)

[[0.09003057 0.24472847 0.66524096]]
