In [1]:
!nvidia-smi

Wed Dec 27 18:13:41 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GT 1030         Off | 00000000:01:00.0  On |                  N/A |
| N/A   31C    P5              N/A /  30W |    424MiB /  2048MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

torch.__version__

ModuleNotFoundError: No module named 'torch'

In [3]:
# scalar
scalar = torch.tensor(7)
scalar.item()

7

In [5]:
scalar.ndim

0

In [6]:
# Vector
vector = torch.tensor([7, 5])
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
vector[1]

tensor(5)

In [12]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [2]:
TENSOR[0][1][2].item()

NameError: name 'TENSOR' is not defined

In [24]:
 ### Random tensors

In [25]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9538, 0.0049, 0.1916, 0.7419],
        [0.1122, 0.4339, 0.7440, 0.4278],
        [0.6113, 0.3101, 0.1935, 0.6374]])

In [27]:
r_i_s_tensor = torch.rand(size=(224, 224, 3))
print(r_i_s_tensor.shape, r_i_s_tensor.ndim )

torch.Size([224, 224, 3]) 3


In [ ]:
# Zeros tensor

zeros = torch.zeros(size=(3, 4))
random_tensor *= zeros
random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
# Creating a range of t

ott = torch.arange(0, 10)

In [ ]:
ten_z = torch.zeros_like(ott)
ten_z

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [ ]:
float_32_tensor.dtype

torch.float64

In [ ]:
float_16_t = float_32_tensor.type(torch.float16)
float_16_t

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_32_tensor * float_16_t).dtype

torch.float64

In [ ]:
# Tensor operations

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
# subtract

tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor.sub(10)

tensor([-9, -8, -7])

In [ ]:
torch.add(tensor, 100)

tensor([101, 102, 103])

In [ ]:
# Matrix mul

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value = tensor[i] * tensor[i]
print(value)

tensor(9)
CPU times: user 597 µs, sys: 0 ns, total: 597 µs
Wall time: 1.49 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 62 µs, sys: 11 µs, total: 73 µs
Wall time: 76.5 µs


tensor(14)

In [ ]:
# Reshaping, viewing and stacking

x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
# adding dimensions
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
# adding dimensions
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x = torch.arange(1., 11.)
x_reshaped = x.reshape(5 , 2)
x_reshaped, x_reshaped.size()

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
# change the view
z = x.view(10)
print(z.size())
z = z.reshape(1, 10)
z

torch.Size([10])


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# stack tensors on top of eachother


x_stacked = torch.stack([z, z, z, z], dim=2)
x_stacked

tensor([[[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]])

In [ ]:
print(z.reshape(2, 5))
z.unsqueeze(0)


tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])


tensor([[[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]])

In [ ]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
y

tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])

In [ ]:
y = torch.squeeze(x, 0)
print(y.size())
y

torch.Size([2, 1, 2, 1, 2])


tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
y = torch.squeeze(x, 1)
print(y.size())
y

torch.Size([2, 2, 1, 2])


tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:, : , 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1 ]

tensor([5])

In [ ]:
x[0, -1, -1]

tensor(9)

In [ ]:
x1 = x[0, :, -1].reshape(1, 3).T
x1

tensor([[3],
        [6],
        [9]])

# PyTorch tensors & NumPy

from_numpy

In [ ]:
import  torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Tensor to NumPy array


In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))