In [2]:
import torch
import numpy as np

np.set_printoptions(precision=3)
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [8]:
t_ones = torch.ones(2, 3)
print(t_ones)
print(t_ones.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])


In [11]:
rand_tensor = torch.rand(2, 3)
print(rand_tensor)

tensor([[0.6795, 0.5235, 0.9343],
        [0.6955, 0.3298, 0.1553]])


In [13]:
t_a_new = t_a.to(torch.int64)
t_a_new.dtype

torch.int64

# Transposing a tensor:

In [15]:
t = torch.rand(3, 5)
t

tensor([[0.2054, 0.6892, 0.0637, 0.3248, 0.7409],
        [0.5772, 0.1820, 0.7177, 0.2485, 0.0158],
        [0.5393, 0.0553, 0.8800, 0.2388, 0.8697]])

In [16]:
t_tr = torch.transpose(t, 0, 1)
print(t.shape, '-->', t_tr.shape)

torch.Size([3, 5]) --> torch.Size([5, 3])


In [17]:
t_tr

tensor([[0.2054, 0.5772, 0.5393],
        [0.6892, 0.1820, 0.0553],
        [0.0637, 0.7177, 0.8800],
        [0.3248, 0.2485, 0.2388],
        [0.7409, 0.0158, 0.8697]])

# Reshaping a tensor (for example, from a 1D vector to a 2D array):

In [20]:
t = torch.zeros(20)
t

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
t_reshape = t.reshape(4, 5)
t_reshape

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

# Removing the unnecessary dimensions 
# (dimensions that have size 1, which are not needed):

In [25]:
t = torch.zeros(1, 2, 1, 4, 1)
t

tensor([[[[[0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.]]]]])

In [26]:
t_sqz = torch.squeeze(t, 2)
t_sqz

tensor([[[[0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.]]]])

In [29]:
print(t.shape, '-->', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1]) --> torch.Size([1, 2, 4, 1])


In [37]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5, 2) - 1
print(t1)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])


In [38]:
t2 = torch.normal(mean=0, std=1, size=(5, 2))
t2

tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])

In [39]:
# compute the element-wise product of t1 and t2
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [40]:
t4 = torch.mean(t1, axis=0)
print(t4)

tensor([-0.1373,  0.2028])


In [41]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [42]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)
print(t6)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])


In [48]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


# Split, stack, and concatenate tensors

In [49]:
torch.manual_seed(1)
t = torch.rand(6)
print(t)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])


In [52]:
t_splits = torch.chunk(t, 3)
[item.numpy() for item in t_splits]

[array([0.758, 0.279], dtype=float32),
 array([0.403, 0.735], dtype=float32),
 array([0.029, 0.8  ], dtype=float32)]

In [55]:
torch.manual_seed(1)
t = torch.rand(5)
print(t)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])


In [57]:
t_splits = torch.split(t, split_size_or_sections=[3, 2])
[item.numpy() for item in t_splits]

[array([0.758, 0.279, 0.403], dtype=float32),
 array([0.735, 0.029], dtype=float32)]

In [58]:
A = torch.ones(3)
A

tensor([1., 1., 1.])

In [61]:
B = torch.zeros(2)
B

tensor([0., 0.])

In [63]:
C = torch.cat([A, B], axis=0)
C

tensor([1., 1., 1., 0., 0.])

In [64]:
A = torch.ones(3)
A

tensor([1., 1., 1.])

In [65]:
B = torch.zeros(3)
B

tensor([0., 0., 0.])

In [66]:
S = torch.stack([A, B], axis=1)
S

tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])

# Building input pipelines in PyTorch